# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Jakub Kadlčík <frostyx@email.cz>, 2015
msgid ""
msgstr ""
"Project-Id-Version: tracer\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-09-10 23:43+0200\n"
"PO-Revision-Date: 2015-04-05 12:35+0000\n"
"Last-Translator: Jakub Kadlčík <frostyx@email.cz>\n"
"Language-Team: Czech (http://www.transifex.com/projects/p/tracer/language/"
"cs/)\n"
"Language: cs\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;\n"

#: ../tracer/views/default.py:59
msgid "Some applications using:"
msgstr "Některé aplikace pomocí:"

#: ../tracer/views/default.py:60
msgid "These applications manually:"
msgstr "Následující aplikace ručně:"

#: ../tracer/views/default.py:61
#, fuzzy
msgid "Uninstalled applications:"
msgstr "Některé aplikace pomocí:"

#: ../tracer/views/default.py:66
msgid "These applications restarting your session:"
msgstr "Následující aplikace restartováním vašeho sezení:"

#: ../tracer/views/default.py:70
msgid "These applications rebooting your computer:"
msgstr "Následující aplikace restartováním počítače:"

#: ../tracer/views/default.py:79 ../tracer/views/interactive.py:11
msgid "You should restart:"
msgstr "Bylo by vhodné restartovat:"

#: ../tracer/views/helper.py:48
msgid "How to restart"
msgstr "Jak restartovat"

#: ../tracer/views/helper.py:52
#, python-brace-format
msgid "It's a part of application called {0}"
msgstr "Součástí aplikace {0}"

#: ../tracer/views/helper.py:63
msgid "Affected by"
msgstr "Ovlivněno kvůi"

#: ../tracer/views/note_for_hidden.py:13
msgid "There are:"
msgstr "Nalezeno:"

#: ../tracer/views/note_for_hidden.py:15
#, fuzzy
msgid "Additionally, there are:"
msgstr "Dále nalezeno:"

#: ../tracer/views/note_for_hidden.py:19
#, python-brace-format
msgid ""
"{0} processes requiring restart of your session (i.e. Logging out & Logging "
"in again)"
msgstr ""
"{0} procesů vyžadujících restart vašeho sezení (i.e. odhlášení a opětovné "
"přihlášení)"

#: ../tracer/views/note_for_hidden.py:24
#, python-brace-format
msgid "{0} processes requiring reboot"
msgstr "{0} procesů vyžadujících reboot"

#: ../tracer/main.py:52
msgid "You will probably need to run tracer as root"
msgstr "Spusťte tracer jako root"

#: ../tracer/resources/applications.py:127 ../tracer/resources/tracer.py:129
msgid "You will have to reboot your computer"
msgstr "Bude potřeba restartovat počítač"

#: ../tracer/resources/applications.py:130
msgid "You will have to log out & log in again"
msgstr "Bude potřeba odhlášení a opětovné přihlášení do systému"

#: ../tracer/resources/exceptions.py:38
#, python-brace-format
msgid ""
"You are running unsupported linux distribution\n"
"\n"
"Please visit https://github.com/FrostyX/tracer/issues\n"
"and create new issue called 'Unknown or unsupported linux distribution: {0} "
"(v{1})' if there isn't such.\n"
"\n"
"Don't you have an GitHub account? Please report this issue on frostyx@email."
"cz"
msgstr ""
"Používáte nepodporovanou linuxovou distribuci.\n"
"\n"
"Prosím navštivte https://github.com/FrostyX/tracer/issues\n"
"a vytvořte nový problém s názvem 'Unknown or unsupported linux distribution: "
"{0} (v{1})', pokud již neexistuje.\n"
"\n"
"Nemáte uživatelský účet na portálu GitHub? Prosím nahlaste problém přes "
"frostyx@email.cz"

#: ../tracer/resources/exceptions.py:53
msgid "Package database is locked by another process"
msgstr "Databáze balíčků je uzamčena jiným procesem"

#: ../tracer/resources/exceptions.py:63
msgid "You can't open package database due to insufficient permissions"
msgstr "Pro otevření databáze balíčků nemáte dostatečné oprávnění "

#: ../tracer/resources/exceptions.py:74
#, python-brace-format
msgid ""
"Problem occurred - neither one of {0} paths exists\n"
"Please contact maintainer of tracer package in your distribution."
msgstr ""
"Vyskytl se problém - ani jedno z {0} umístění neexistuje.\n"
"Prosím kontaktuje správce balíčku tracer pro vaši distribuci."

#: ../tracer/controllers/default.py:104
msgid "Press application number for help or 'q' to quit"
msgstr "Pro zobrazení nápovědy zadejte číslo aplikace. Nebo 'q' pro ukončení"

#: ../tracer/controllers/default.py:112
msgid "Wrong application number"
msgstr "Neplatné číslo aplikace"

#: ../tracer/controllers/default.py:114
msgid "Press <enter> to get list of applications"
msgstr "Pro vypsání seznamu aplikací stisknete <enter>"

#: ../tracer/controllers/helper.py:58
msgid "You don't have enough permissions"
msgstr "Nemáte dostatečné oprávnění"

#: ../tracer/controllers/helper.py:70
#, python-brace-format
msgid "Application called {0} is not running"
msgstr "Aplikace s názvem {0} není v tuto chvíli spuštěna"

#~ msgid "Only root can use this application"
#~ msgstr "Tato aplikace vyžaduje oprávnění uživatele root"
